apiVersion: v1
kind: Service
metadata:
  name: hugo
  namespace: hugo
spec:
  selector:
    app: hugo
  ports:
  - name: http
    targetPort: 80
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo
  namespace: hugo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
      - name: hugo
        image: yourdockerhubname:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
